"""Reference stimulation values used by examples and research experiments."""

STANDARD_AMPLITUDE_UA = 60.0
STANDARD_FREQUENCY_HZ = 300.0
STANDARD_PULSE_WIDTH_US = 170.0
STANDARD_APPEARANCE_THRESHOLD_UA = 30.0

__all__ = [
    "STANDARD_AMPLITUDE_UA",
    "STANDARD_APPEARANCE_THRESHOLD_UA",
    "STANDARD_FREQUENCY_HZ",
    "STANDARD_PULSE_WIDTH_US",
]
